# -*- coding: utf-8 -*-

{
    'name': 'WeChat',
    'version': '1.0.0',
    'category': 'Social Network',
    'summary': '微信公众号的接入与管理',
    'author': 'e2yun',
    'website': '',
    'application': True,
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/wx_init_data.xml',
        'views/parent_menus.xml',
        'views/wx_action_act_article_views.xml',
        'views/wx_action_act_custom_views.xml',
        'views/wx_action_act_text_views.xml',
        'views/wx_articlesreply_article_views.xml',
        'views/wx_autoreply_views.xml',
        'views/wx_config_settings_views.xml',
        'views/wx_menu_item_left_views.xml',
        'views/wx_menu_item_middle_views.xml',
        'views/wx_menu_item_right_views.xml',
        'views/wx_menu_views.xml',
        'views/wx_user_group_views.xml',
        'views/wx_user_views.xml',
        'views/wx_config_corpsettings_views.xml',
        'views/wx_corpuser_views.xml',
        'views/wx_confirm_views.xml',
        'views/wx_app_config_views.xml',
        'views/wx_media_views.xml',
        'views/wx_approval_record_views.xml',
        'views/wx_media_article_views.xml',
        'views/wx_send_mass_views.xml',
        'views/wx_config_views.xml',
        'views/res_users_views.xml',
        'views/res_partner_views.xml',
        'views/wx_userodoouser.xml',
        'views/crm_team_views.xml',
        'views/wx_para_config.xml',
        'views/wx_trace_log.xml',
        'views/wx_trace_log_type.xml',

    ],
    'qweb': [
    ],
    'depends': ['base', 'web', 'im_livechat', 'sale_management'],
    'installable': True,
    'auto_install': True,
    'active': False,
    'web': True,
}
