# coding=utf-8
from . import corpuser_uuid
from . import crm_team
from . import livechat_channel
from . import mail_channel
from . import menu_about_models
from . import reply_about_models
from . import res_company
from . import res_config_settings
from . import res_partner
from . import res_users
from . import sale_coupon_program
from . import sale_make_invoice_advance
from . import user_models
from . import wx_app_config
from . import wx_approval_record
from . import wx_autoreply_model
from . import wx_config
from . import wx_config_model
from . import wx_confirm_wizard
from . import wx_media
from . import wx_par_config
# from . import wx_sale_order
from . import wx_send_mass
from . import wx_tracelog
from . import wx_userodoouser
from . import wxuser_uuid
from . import product
from . import change_res_partner
